name: "Deploy the portfolio"

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  deploy_source:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: "18.x"
    steps:
      ## Checkout Repo
      - uses: actions/checkout@v4
      
      ## Set up Node.js
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      ## Install npm dependencies and Build Dist
      - name: Install dependencies
        run: npm install
      
      - name: Build project
        run: npm run build

      ## Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -f build
          git commit -m 'Deploy to GitHub Pages'
          git push origin `git subtree split --prefix build develop`:gh-pages --force
